// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://haglswqbicwduxqltzcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhZ2xzd3FiaWN3ZHV4cWx0emNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MTYxMTIsImV4cCI6MjA1NzM5MjExMn0.JWD07vbN85MyfnV7mcplGgAaK2mFZjwN_JIU0-rB3cE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);