
import { AuditTrail } from './types';

// Mock data for audit trail
export const mockAuditTrail: AuditTrail[] = [
  {
    id: '1',
    date: new Date(2023, 9, 15, 10, 30),
    userId: 'user123',
    userName: 'João Silva',
    userRole: 'Analista',
    action: 'calculation',
    resourceType: 'tax_credit',
    resourceId: 'CR-0123',
    resourceName: 'Crédito Tributário - Empresa ABC',
    details: 'Cálculo de retenção IRRF realizado',
    ipAddress: '192.168.1.1',
  },
  {
    id: '2',
    date: new Date(2023, 9, 15, 11, 45),
    userId: 'user456',
    userName: 'Maria Souza',
    userRole: 'Supervisor',
    action: 'update',
    resourceType: 'tax_credit',
    resourceId: 'CR-0123',
    resourceName: 'Crédito Tributário - Empresa ABC',
    details: 'Atualização de valor base de cálculo',
    ipAddress: '192.168.1.2',
  },
  {
    id: '3',
    date: new Date(2023, 9, 15, 14, 20),
    userId: 'user789',
    userName: 'Carlos Mendes',
    userRole: 'Administrador',
    action: 'status_change',
    resourceType: 'tax_credit',
    resourceId: 'CR-0123',
    resourceName: 'Crédito Tributário - Empresa ABC',
    details: 'Alteração de status do crédito',
    ipAddress: '192.168.1.3',
    previousStatus: 'PENDING',
    newStatus: 'APPROVED',
  },
  {
    id: '4',
    date: new Date(2023, 9, 16, 9, 15),
    userId: 'user123',
    userName: 'João Silva',
    userRole: 'Analista',
    action: 'calculation',
    resourceType: 'tax_credit',
    resourceId: 'CR-0456',
    resourceName: 'Crédito Tributário - Empresa XYZ',
    details: 'Cálculo de correção monetária realizado',
    ipAddress: '192.168.1.1',
  },
  {
    id: '5',
    date: new Date(2023, 9, 16, 10, 30),
    userId: 'user456',
    userName: 'Maria Souza',
    userRole: 'Supervisor',
    action: 'export',
    resourceType: 'report',
    resourceId: 'REP-789',
    resourceName: 'Relatório Mensal de Créditos',
    details: 'Exportação de relatório em PDF',
    ipAddress: '192.168.1.2',
  },
  {
    id: '6',
    date: new Date(2023, 9, 17, 11, 45),
    userId: 'user789',
    userName: 'Carlos Mendes',
    userRole: 'Administrador',
    action: 'create',
    resourceType: 'tax_credit',
    resourceId: 'CR-0789',
    resourceName: 'Crédito Tributário - Empresa DEF',
    details: 'Criação de novo crédito tributário',
    ipAddress: '192.168.1.3',
  },
  {
    id: '7',
    date: new Date(2023, 9, 17, 14, 15),
    userId: 'user123',
    userName: 'João Silva',
    userRole: 'Analista',
    action: 'update',
    resourceType: 'supplier',
    resourceId: 'SUP-456',
    resourceName: 'Fornecedor ABC Serviços',
    details: 'Atualização de CNAE do fornecedor',
    ipAddress: '192.168.1.1',
  },
  {
    id: '8',
    date: new Date(2023, 9, 18, 9, 30),
    userId: 'user456',
    userName: 'Maria Souza',
    userRole: 'Supervisor',
    action: 'import',
    resourceType: 'data_batch',
    resourceId: 'IMP-123',
    resourceName: 'Lote de Notas Fiscais',
    details: 'Importação de lote de notas fiscais do cliente',
    ipAddress: '192.168.1.2',
  },
  {
    id: '9',
    date: new Date(2023, 9, 18, 11, 15),
    userId: 'user789',
    userName: 'Carlos Mendes',
    userRole: 'Administrador',
    action: 'delete',
    resourceType: 'calculation',
    resourceId: 'CALC-789',
    resourceName: 'Cálculo Tributário',
    details: 'Exclusão de cálculo duplicado',
    ipAddress: '192.168.1.3',
  },
  {
    id: '10',
    date: new Date(2023, 9, 19, 10, 45),
    userId: 'user123',
    userName: 'João Silva',
    userRole: 'Analista',
    action: 'status_change',
    resourceType: 'tax_credit',
    resourceId: 'CR-0456',
    resourceName: 'Crédito Tributário - Empresa XYZ',
    details: 'Alteração de status do crédito',
    ipAddress: '192.168.1.1',
    previousStatus: 'ANALYZING',
    newStatus: 'RECOVERED',
  },
];

export const getUniqueUsers = () => {
  return Array.from(new Set(mockAuditTrail.map(a => a.userId)))
    .map(userId => {
      const user = mockAuditTrail.find(a => a.userId === userId);
      return {
        id: userId,
        name: user ? user.userName : '',
      };
    });
};
